### ISSUE TITLE
 Plase include my plugin in you native

### ISSUE THREAD

**Issue by Valeryn4** [DrMoriarty/godot-firebase-core#1]
Hello. Plase include my plugin in you native lib: https://github.com/Valeryn4/GodotGoogleInAppReview

**Comment by DrMoriarty** [comment]
Hello @Valeryn4 !
You can do it youself, the process described at https://github.com/DrMoriarty/nativelib-cli#publishing-at-github
Feel free to ask me if you faced any problems

**Comment by Valeryn4** [comment]
It's hard for me to do this from Windows. = (

**Comment by DrMoriarty** [comment]
Ok, I understand.
I will prepare all needed files and upload it.

**Comment by DrMoriarty** [comment]
@Valeryn4 did you tried this plugin?
https://github.com/DrMoriarty/godot-rateme

**Comment by DrMoriarty** [comment]
if you have found some bugs or plugin's behaviour doesn't fit any circumstances I'd prefer you make an issue for this plugin (or maybe PR with fixes or new functionality)

**Comment by Valeryn4** [comment]
owh...

I have not seen him ...

He only has a problem with the iPhone 14+.
https://stackoverflow.com/questions/63953891/requestreview-was-deprecated-in-ios-14-0

**Comment by DrMoriarty** [comment]
@Valeryn4 
I updated RateMe for iOS 14+ and Godot 3.3-stable.
Check it and feel free to open issues if you faced any problems.
